/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
(function(d,k,h){try{__qc("defaults",d,{labels:"_fp.event.Default"})}catch(t){}var n="twitter:title og:title title author authors article:author article:authors bt:author bt:authors sailthru.author sailthru.authors sailthru.title lv:author lv:authors lv:title".split(" "),p=function(a){return a.replace(/^[\s\ufeff\xA0]+|[\s\ufeff\xA0]+$/g,"")},q=function(a){return{}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()},r=function(a,b,e){return a?"nc"===a?!b||!e||0>b.indexOf(e):"eq"===a?b===e:"sw"===
a?0===b.indexOf(e):"ew"===a?(a=b.length-e.length,b=b.lastIndexOf(e,a),-1!==b&&b===a):"c"===a?0<=b.indexOf(e):!1:!1},m=function(a){var b=h.createElement("a");b.href=a;return b},g=function(a,b,e){var c;c=k.top===k.self?h.location.href:m(h.referrer).href;r(b,c,e)?a(c):a(!1)},l=function(a){return{labels:a}},f=function(a){return"array"===q(a)?l(a.join(",")):l(""+a)},s=["rules",[d,null,[[f,"_fp.event.Homepage"]],[[function(a,b,e){var c;c=k.top===k.self?h.location.pathname:m(h.referrer).pathname;r(b,c,e)?
a(c):a(!1)},"eq","/"]]],[d,null,[[f,"_fp.event.Website Landing Page"]],[[g,"c","wordpress.com/website"]]],[d,null,[[f,"_fp.event.Easy Steps Landing Page"]],[[g,"c","wordpress.com/easy"]]],[d,null,[[f,"_fp.event.Create Landing Page"]],[[g,"c","wordpress.com/create"]]],[d,null,[[f,"_fp.event.Personal Landing Page"]],[[g,"c","wordpress.com/personal"]]],[d,null,[[f,"_fp.event.Business Landing Page"]],[[g,"c","wordpress.com/business"]]],[d,null,[[f,"_fp.event.Brand Everywhere Landing Page"]],[[g,"c","wordpress.com/brand-everywhere"]]],
[d,null,[[f,"_fp.event.Business Everywhere Landing Page"]],[[g,"c","wordpress.com/business-everywhere"]]],[d,null,[[f,"_fp.event.Remove Ads Landing Page"]],[[g,"c","wordpress.com/remove-ads"]]],[d,null,[[function(a,b){var e=[],c;if("array"===q(b)){for(c=0;c<b.length;c++)e.push(a+"."+b[c]);return l(e.join(","))}return l(a+"."+b)},"_fp.title"]],[[function(a,b,e){b=document.getElementsByTagName("meta");for(var c,d,f=0;f<b.length;f++)if(c=b[f],d=c.getAttribute("name")||c.getAttribute("property"),d==e){b=
c.getAttribute("content");c=d=c=void 0;b:{c=void 0;for(c=0;c<n.length;c++)if(n[c]===e){c=!1;break b}c=!0}if(b)if(c){d=b.split(",");for(c=0;c<d.length;c++)d[c]=p(d[c]);e=d}else e=p(b.replace(/,+/g," "));else e=b;a(e);return}a(!1)},"exactmatch","og:title"]]],[d,null,[[f,"_fp.event.Start - Themes"]],[[g,"eq","https://wordpress.com/start/themes"]]],[d,null,[[f,"_fp.event.Step 1 - Lets Create Your New Site"]],[[g,"eq","https://wordpress.com/start/design-type-with-store?ref\x3dhomepage"]]],[d,null,[[f,
"_fp.event.Step 3 - Domains"]],[[g,"eq","https://wordpress.com/start/domains"]]],[d,null,[[f,"_fp.event.Step 4 - Plans"]],[[g,"eq","https://wordpress.com/start/plans"]]],[d,null,[[f,"_fp.event.Step 5 - User Account"]],[[g,"eq","https://wordpress.com/start/user"]]],[d,null,[[f,"_fp.subchannel.Checkout Process"]],[[g,"sw","https://wordpress.com/checkout/"]]]];__qc.apply(null,s);(function(){var a=function(){return k.top===k.self?h.location.href:m(h.referrer).href},b=a();setInterval(function(){var e=
a();e!==b&&(b=e,__qc.apply(null,s),__qc("push",{qacct:d,event:"load"},!0))},2E3)})()})("p-3Ma3jHaQMB_bS",window,document);